{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nagios-plugins-collection.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "nagios-plugins-collection.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
