apiVersion: v2
name: nagios-plugins-collection
version: 2.0.0
appVersion: "2.0.0"
description: Run Nagios plugins as Kubernetes CronJobs/Jobs
keywords:
  - nagios
  - monitoring
  - plugins
maintainers:
  - name: Thomas Vincent
    email: thomasvincent@gmail.com
