# SPDX-FileCopyrightText: 2025 Thomas Vincent
# SPDX-License-Identifier: Apache-2.0
version = 1

[[annotations]]
path = [".github/renovate.json", "LICENSE", "docker/mocks/wiremock/mappings/es_critical.json", "docker/mocks/wiremock/mappings/es_ok.json", "docker/mocks/wiremock/mappings/es_warning.json", "docker/mocks/wiremock/mappings/prom_critical.json", "docker/mocks/wiremock/mappings/prom_ok.json", "docker/mocks/wiremock/mappings/prom_warn.json", "docker/mocks/wiremock/mappings/token.json", "packaging/license-policy.json", "packaging/platform-support.json"]
precedence = "closest"
SPDX-FileCopyrightText = "2025 Thomas Vincent"
SPDX-License-Identifier = "Apache-2.0"
