name: Dependabot auto-merge

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot metadata
        id: meta
        \108eff52bf64351f401fb50d4972fa95b9f2c2d1b
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Enable auto-merge for patch updates
        if: steps.meta.outputs.update-type == 'version-update:semver-patch'
        \145fc124d949b19b6b8bf6645b6c9d55f4f9ac61a
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: patch
          merge-method: squash
