name: Publish to GitHub Packages

on:
  release:
    types: [published]
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - \18e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          fetch-depth: 0
      - name: Set up Python
        \183679a892e2d95755f2dac6acb0bfd1e9ac5d548
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Build package
        run: |
          python -m pip install --upgrade pip
          pip install build twine
          python -m build
          python -m twine check dist/*
      - name: Publish to GitHub Packages
        env:
          TWINE_USERNAME: ${{ github.actor }}
          TWINE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m twine upload --repository-url https://pypi.pkg.github.com/${{ github.repository_owner }} dist/*
